-- MySQL Script generated by MySQL Workbench
-- Mon Sep 14 14:50:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_matriculas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_matriculas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_matriculas` DEFAULT CHARACTER SET utf8 ;
USE `sistema_matriculas` ;

-- -----------------------------------------------------
-- Table `sistema_matriculas`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`rol` (
  `rol_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(150) NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`usuario` (
  `usuario_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rol_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(150) NULL,
  `fecha_nacimiento` DATE NULL,
  `dni` VARCHAR(15) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `direccion` VARCHAR(150) NULL,
  `fecha_registro` TIME NULL,
  `fecha_actualizacion` DATE NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `foreign_rol_idx` (`rol_id` ASC),
  CONSTRAINT `foreign_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `sistema_matriculas`.`rol` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`apoderado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`apoderado` (
  `apoderado_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `grado_instruccion` VARCHAR(100) NULL,
  `oficio` VARCHAR(100) NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`apoderado_id`),
  INDEX `foreign_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `foreign_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sistema_matriculas`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`alumno` (
  `alumno_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apoderado_id` INT UNSIGNED NOT NULL,
  `numero_hermanos` INT NULL,
  `colegio_procedencia` VARCHAR(100) NULL,
  `observaciones` VARCHAR(150) NULL,
  `alumno_vive_con` VARCHAR(100) NULL,
  `alumno_retira_solo` TINYINT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alumno_id`),
  INDEX `foreign_apoderado_idx` (`apoderado_id` ASC),
  INDEX `foreign_usuario_alumno_idx` (`usuario_id` ASC),
  CONSTRAINT `foreign_apoderado`
    FOREIGN KEY (`apoderado_id`)
    REFERENCES `sistema_matriculas`.`apoderado` (`apoderado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_usuario_alumno`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sistema_matriculas`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`anio_lectivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`anio_lectivo` (
  `anio_lectivo_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `anio_inicio` VARCHAR(45) NULL,
  `anio_fin` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`anio_lectivo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`seccion` (
  `seccion_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(150) NULL,
  PRIMARY KEY (`seccion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`grado` (
  `grado_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `seccion_id` INT UNSIGNED NOT NULL,
  `descripcion` VARCHAR(150) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`grado_id`),
  INDEX `foreign_seccion_idx` (`seccion_id` ASC),
  CONSTRAINT `foreign_seccion`
    FOREIGN KEY (`seccion_id`)
    REFERENCES `sistema_matriculas`.`seccion` (`seccion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`matricula` (
  `matricula_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NOT NULL,
  `grado_id` INT UNSIGNED NOT NULL,
  `anio_lectivo_id` INT UNSIGNED NOT NULL,
  `valor_matricula` DOUBLE NULL,
  `valor_pension` DOUBLE NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`matricula_id`),
  INDEX `foreign_usuario_matri_idx` (`usuario_id` ASC),
  INDEX `foreign_anio_lectivo_idx` (`anio_lectivo_id` ASC),
  INDEX `foreign_grado_idx` (`grado_id` ASC),
  CONSTRAINT `foreign_usuario_matri`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sistema_matriculas`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_anio_lectivo`
    FOREIGN KEY (`anio_lectivo_id`)
    REFERENCES `sistema_matriculas`.`anio_lectivo` (`anio_lectivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_grado`
    FOREIGN KEY (`grado_id`)
    REFERENCES `sistema_matriculas`.`grado` (`grado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`pension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`pension` (
  `pension_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `matricula_id` INT UNSIGNED NOT NULL,
  `numero_pension` INT NULL,
  `monto` DOUBLE NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`pension_id`),
  INDEX `foreign_matricula_idx` (`matricula_id` ASC),
  CONSTRAINT `foreign_matricula`
    FOREIGN KEY (`matricula_id`)
    REFERENCES `sistema_matriculas`.`matricula` (`matricula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`pago` (
  `pago_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `matricula_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `pension_id` INT UNSIGNED NOT NULL,
  `valor` DOUBLE NULL,
  `descripcion` VARCHAR(150) NULL,
  PRIMARY KEY (`pago_id`),
  INDEX `foreign_matricula_idx` (`matricula_id` ASC),
  INDEX `foreign_usuario_pago_idx` (`usuario_id` ASC),
  INDEX `foreign_pension_idx` (`pension_id` ASC),
  CONSTRAINT `foreign_matricula_pago`
    FOREIGN KEY (`matricula_id`)
    REFERENCES `sistema_matriculas`.`matricula` (`matricula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_usuario_pago`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sistema_matriculas`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_pension`
    FOREIGN KEY (`pension_id`)
    REFERENCES `sistema_matriculas`.`pension` (`pension_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`detalle_comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`detalle_comprobante` (
  `detalle_comprobante_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `descripcion` VARCHAR(100) NULL,
  `precio_unitario` DOUBLE NULL,
  `subtotal` DOUBLE NULL,
  `descuento` DOUBLE NULL,
  `igv` DOUBLE NULL,
  `total` DOUBLE NULL,
  PRIMARY KEY (`detalle_comprobante_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_matriculas`.`comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_matriculas`.`comprobante` (
  `comprobante_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apoderado_id` INT UNSIGNED NOT NULL,
  `pago_id` INT UNSIGNED NOT NULL,
  `detalle_comprobante_id` INT UNSIGNED NOT NULL,
  `ruc` INT NULL,
  `direccion` VARCHAR(100) NULL,
  `telefono` VARCHAR(45) NULL,
  `fecha_emision` TIMESTAMP NULL,
  `anio_lectivo` VARCHAR(45) NULL,
  PRIMARY KEY (`comprobante_id`),
  INDEX `foreign_apoderado_comp_idx` (`apoderado_id` ASC),
  INDEX `foreign_pago_idx` (`pago_id` ASC),
  INDEX `foreign_detalle_idx` (`detalle_comprobante_id` ASC),
  CONSTRAINT `foreign_apoderado_comp`
    FOREIGN KEY (`apoderado_id`)
    REFERENCES `sistema_matriculas`.`apoderado` (`apoderado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_pago`
    FOREIGN KEY (`pago_id`)
    REFERENCES `sistema_matriculas`.`pago` (`pago_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `foreign_detalle`
    FOREIGN KEY (`detalle_comprobante_id`)
    REFERENCES `sistema_matriculas`.`detalle_comprobante` (`detalle_comprobante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
